[0m15:34:34.046293 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca3210a3fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca3217cd7e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca3217cd750>]}


============================== 15:34:34.048557 | 5946a57f-1c5f-4e79-ac6b-96aadb5b1bb3 ==============================
[0m15:34:34.048557 [info ] [MainThread]: Running with dbt=1.6.18
[0m15:34:34.049008 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/kidem/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:34:34.049422 [info ] [MainThread]: dbt version: 1.6.18
[0m15:34:34.049706 [info ] [MainThread]: python version: 3.10.12
[0m15:34:34.049986 [info ] [MainThread]: python path: /home/kidem/projects/data-engineering-zoomcamp/04-analytics-engineering/.venv/bin/python3
[0m15:34:34.050257 [info ] [MainThread]: os info: Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[0m15:34:34.050548 [info ] [MainThread]: Using profiles dir at /home/kidem/.dbt
[0m15:34:34.050798 [info ] [MainThread]: Using profiles.yml file at /home/kidem/.dbt/profiles.yml
[0m15:34:34.051024 [info ] [MainThread]: Using dbt_project.yml file at /home/kidem/projects/data-engineering-zoomcamp/04-analytics-engineering/dbt_project.yml
[0m15:34:34.051265 [info ] [MainThread]: Configuration:
[0m15:34:34.051536 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m15:34:34.051771 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:34:34.052013 [info ] [MainThread]: Required dependencies:
[0m15:34:34.052283 [debug] [MainThread]: Executing "git --help"
[0m15:34:34.057544 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m15:34:34.058069 [debug] [MainThread]: STDERR: "b''"
[0m15:34:34.058342 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m15:34:34.058746 [info ] [MainThread]: Connection test skipped since no profile was found
[0m15:34:34.059135 [info ] [MainThread]: [31m2 checks failed:[0m
[0m15:34:34.059454 [info ] [MainThread]: dbt looked for a profiles.yml file in /home/kidem/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m15:34:34.059797 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/kidem/projects/data-engineering-zoomcamp/04-analytics-engineering/dbt_project.yml> not found

[0m15:34:34.060512 [debug] [MainThread]: Command `dbt debug` failed at 15:34:34.060339 after 0.02 seconds
[0m15:34:34.060925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca3210a3fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca3217cd840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca3217ce080>]}
[0m15:34:34.061270 [debug] [MainThread]: Flushing usage events
[0m17:20:40.948732 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x714e843a1cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x714e82453210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x714e8247abd0>]}


============================== 17:20:40.957410 | 39ead030-2ac7-4425-a140-3c941fb8d354 ==============================
[0m17:20:40.957410 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:20:40.958118 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m17:20:40.959103 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:20:40.960989 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.054079235, "process_user_time": 0.985914, "process_kernel_time": 0.17352, "process_mem_max_rss": "85708", "process_in_blocks": "28112", "process_out_blocks": "1016", "command_success": false}
[0m17:20:40.961475 [debug] [MainThread]: Command `dbt deps` failed at 17:20:40.961378 after 0.05 seconds
[0m17:20:40.961798 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x714e8249fb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x714e8263d350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x714e82479a10>]}
[0m17:20:40.962156 [debug] [MainThread]: Flushing usage events
[0m17:21:33.469311 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78b416aeb6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78b416af08d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78b416af1e50>]}


============================== 17:21:33.473498 | 28e43b15-860c-406e-a68a-6b0bf5697452 ==============================
[0m17:21:33.473498 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:21:33.473947 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:21:33.474364 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:21:33.475013 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.034654006, "process_user_time": 0.758537, "process_kernel_time": 0.090395, "process_mem_max_rss": "85768", "process_out_blocks": "1016", "command_success": false, "process_in_blocks": "0"}
[0m17:21:33.475375 [debug] [MainThread]: Command `dbt deps` failed at 17:21:33.475283 after 0.04 seconds
[0m17:21:33.475628 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78b416ca92d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78b416b0a110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78b41a4e4c10>]}
[0m17:21:33.475857 [debug] [MainThread]: Flushing usage events
[0m17:25:06.743289 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7850b91adb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7850b91a5fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7850b918f950>]}


============================== 17:25:06.750726 | 131f9f3f-9fe9-48f6-8966-79a704e8425a ==============================
[0m17:25:06.750726 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:25:06.751292 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/root/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:25:06.751834 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:25:06.753282 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.047426082, "process_user_time": 1.143161, "process_kernel_time": 0.18072, "process_mem_max_rss": "85592", "process_in_blocks": "28072", "process_out_blocks": "1016", "command_success": false}
[0m17:25:06.753786 [debug] [MainThread]: Command `dbt deps` failed at 17:25:06.753686 after 0.05 seconds
[0m17:25:06.754133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7850b91ca110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7850b9365210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7850bcb8cc10>]}
[0m17:25:06.754466 [debug] [MainThread]: Flushing usage events
[0m17:32:20.158218 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75731f51f750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75731fc10850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75731f6d6d10>]}


============================== 17:32:20.165259 | 0e7c8454-1959-4690-be3c-afffb0fa52e0 ==============================
[0m17:32:20.165259 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:32:20.165709 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:32:20.166137 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:32:20.167767 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.048695832, "process_user_time": 1.108613, "process_kernel_time": 0.283222, "process_mem_max_rss": "84684", "process_in_blocks": "35720", "process_out_blocks": "1016", "command_success": false}
[0m17:32:20.168139 [debug] [MainThread]: Command `dbt deps` failed at 17:32:20.168065 after 0.05 seconds
[0m17:32:20.168452 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75731f6e12d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75731f541dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x757322eec350>]}
[0m17:32:20.168695 [debug] [MainThread]: Flushing usage events
[0m17:34:27.080197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7437eea40550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7437ee882dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7437eea413d0>]}


============================== 17:34:27.083611 | ada70f2b-72fc-49a3-a9e6-85afcef3540d ==============================
[0m17:34:27.083611 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:34:27.084210 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt deps', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:34:27.084831 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:34:27.085776 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.056467127, "process_user_time": 1.37088, "process_kernel_time": 0.202468, "process_mem_max_rss": "84684", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m17:34:27.086379 [debug] [MainThread]: Command `dbt deps` failed at 17:34:27.086226 after 0.06 seconds
[0m17:34:27.086757 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7437ee8816d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7437eea48990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7437eede86d0>]}
[0m17:34:27.087110 [debug] [MainThread]: Flushing usage events
